nutrition_data = {
    "idli": {"calories": 39, "protein": 1.4, "carbs": 7.8, "fat": 0.2, "fiber": 0.6, "sugar": 0.1, "vitamin_c": 0, "iron": 0.3},
    "dosa": {"calories": 120, "protein": 3, "carbs": 25, "fat": 2, "fiber": 1, "sugar": 1, "vitamin_c": 0, "iron": 0.5},
    "masala dosa": {"calories": 168, "protein": 4, "carbs": 33, "fat": 3, "fiber": 3, "sugar": 2, "vitamin_c": 1, "iron": 1},
    "uttapam": {"calories": 150, "protein": 5, "carbs": 28, "fat": 2, "fiber": 2, "sugar": 1, "vitamin_c": 1, "iron": 0.5},
    "upma": {"calories": 158, "protein": 4, "carbs": 30, "fat": 3, "fiber": 2, "sugar": 1, "vitamin_c": 1, "iron": 0.8},
    "poha": {"calories": 209, "protein": 5, "carbs": 40, "fat": 4, "fiber": 3, "sugar": 2, "vitamin_c": 2, "iron": 1.2},
    "vada": {"calories": 120, "protein": 3, "carbs": 15, "fat": 6, "fiber": 1, "sugar": 0, "vitamin_c": 0, "iron": 0.5},
    "medu vada": {"calories": 150, "protein": 4, "carbs": 18, "fat": 8, "fiber": 2, "sugar": 0, "vitamin_c": 0, "iron": 0.6},
    "sambar": {"calories": 90, "protein": 5, "carbs": 12, "fat": 2, "fiber": 4, "sugar": 2, "vitamin_c": 4, "iron": 1.5},
    "rasam": {"calories": 30, "protein": 1, "carbs": 5, "fat": 0, "fiber": 1, "sugar": 0, "vitamin_c": 3, "iron": 0.5},
    "curd rice": {"calories": 220, "protein": 6, "carbs": 30, "fat": 4, "fiber": 1, "sugar": 5, "vitamin_c": 2, "iron": 0.5},
    "lemon rice": {"calories": 200, "protein": 4, "carbs": 35, "fat": 4, "fiber": 2, "sugar": 1, "vitamin_c": 8, "iron": 1},
    "tamarind rice": {"calories": 210, "protein": 4, "carbs": 38, "fat": 3, "fiber": 2, "sugar": 1, "vitamin_c": 2, "iron": 1},
    "pongal": {"calories": 250, "protein": 7, "carbs": 40, "fat": 7, "fiber": 3, "sugar": 2, "vitamin_c": 1, "iron": 1.2},
    "vada pav": {"calories": 250, "protein": 6, "carbs": 40, "fat": 10, "fiber": 5, "sugar": 4, "vitamin_c": 2, "iron": 2},
    "coconut chutney": {"calories": 80, "protein": 1, "carbs": 3, "fat": 7, "fiber": 1, "sugar": 1, "vitamin_c": 1, "iron": 0.3},
    "tomato chutney": {"calories": 50, "protein": 1, "carbs": 10, "fat": 1, "fiber": 2, "sugar": 5, "vitamin_c": 10, "iron": 0.5},
    "sundal": {"calories": 150, "protein": 8, "carbs": 20, "fat": 2, "fiber": 6, "sugar": 2, "vitamin_c": 2, "iron": 2},
    "banana": {"calories": 89, "protein": 1, "carbs": 23, "fat": 0.3, "fiber": 2.6, "sugar": 12, "vitamin_c": 8.7, "iron": 0.3},
    "pongal ven pongal": {"calories": 240, "protein": 6, "carbs": 42, "fat": 6, "fiber": 3, "sugar": 2, "vitamin_c": 1, "iron": 1},
    "bisi bele bath": {"calories": 260, "protein": 8, "carbs": 45, "fat": 7, "fiber": 4, "sugar": 3, "vitamin_c": 2, "iron": 1.5},
    "apam": {"calories": 120, "protein": 2, "carbs": 25, "fat": 2, "fiber": 1, "sugar": 0, "vitamin_c": 0, "iron": 0.5},
    "paniyaram": {"calories": 140, "protein": 3, "carbs": 18, "fat": 5, "fiber": 1, "sugar": 1, "vitamin_c": 0, "iron": 0.5},
    "kesari bath": {"calories": 180, "protein": 3, "carbs": 35, "fat": 5, "fiber": 1, "sugar": 15, "vitamin_c": 0, "iron": 0.5},
    "neer dosa": {"calories": 110, "protein": 2, "carbs": 22, "fat": 1, "fiber": 1, "sugar": 0, "vitamin_c": 0, "iron": 0.5},
    "rava dosa": {"calories": 130, "protein": 3, "carbs": 28, "fat": 2, "fiber": 1, "sugar": 1, "vitamin_c": 0, "iron": 0.5},
    "idiyappam": {"calories": 100, "protein": 2, "carbs": 22, "fat": 1, "fiber": 1, "sugar": 0, "vitamin_c": 0, "iron": 0.5}
}

